# Generated by Django 3.0.5 on 2020-12-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
