# Generated by Django 3.0.5 on 2020-12-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='brand',
            field=models.CharField(max_length=60),
        ),
    ]
